### ISSUE TITLE
Provide an example of the authentication process

### ISSUE THREAD

**Issue by polchky** [cryptograph/stealthdb#1]
Hi, 
I think it would be great if an example project could be given, in particular one that would illustrate the remote client authentication mechanism.

**Comment by xvzcf** [comment]
The mechanism you're referring to is encapsulated by what the StealthDB paper calls the "Auth" enclave, for which the implementation is not available yet. Otherwise, in the near future we will add some sample schemas and data with which the user can explore the capabilities of StealthDB.

**Comment by polchky** [comment]
Sounds great, I'm looking forward to see this!
